/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/**
 *
 * @author Aspire
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialogInfo = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JLabelCrupier = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jPanelRight = new javax.swing.JPanel();
        jButtonRules = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldTexas = new javax.swing.JTextField();
        jTextFieldPoker = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jPanelLeft = new javax.swing.JPanel();
        jPanelUp = new javax.swing.JPanel();

        JDialogInfo.setTitle("Information");
        JDialogInfo.setAlwaysOnTop(true);
        JDialogInfo.setBackground(new java.awt.Color(27, 2, 2));
        JDialogInfo.setForeground(new java.awt.Color(27, 2, 2));
        JDialogInfo.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Spades.jpg")).getImage());
        JDialogInfo.setPreferredSize(new java.awt.Dimension(400, 250));
        JDialogInfo.setResizable(false);
        JDialogInfo.setSize(new java.awt.Dimension(400, 250));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(27, 2, 2));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 252, 182));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(10);
        jTextArea1.setTabSize(4);
        jTextArea1.setText("\t  Texas Hold'em Poker Game Info.\n\nThis game was developed for a final project of programming subject in the Science faculty, UNAM, México.\n\nI am a applied math student, not a designer, so, the graphics are poorly (like my english) :c\n\nHowever, I had more care in the game engine, it won't dissapoint you.\n\nJava documentation and code \"are in spanish\", but the code of game is very simple and friendly.\n\nCard's design have been obtained from this blog: \nhttps://byronknoll.blogspot.com/2011/03/vector-playing-cards.html\n\nOther imagen was obtained from google images search's.\n\n        More details in the game code ¡Have fun!\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jTextArea1.setMaximumSize(new java.awt.Dimension(400, 480));
        jTextArea1.setMinimumSize(new java.awt.Dimension(400, 480));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout JDialogInfoLayout = new javax.swing.GroupLayout(JDialogInfo.getContentPane());
        JDialogInfo.getContentPane().setLayout(JDialogInfoLayout);
        JDialogInfoLayout.setHorizontalGroup(
            JDialogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        JDialogInfoLayout.setVerticalGroup(
            JDialogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Texas Hold'em Póker");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Constantia", 3, 14)); // NOI18N
        setForeground(java.awt.Color.magenta);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Spades.jpg")).getImage());
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("inicio"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        JLabelCrupier.setBackground(new java.awt.Color(27, 2, 2));
        JLabelCrupier.setForeground(new java.awt.Color(27, 2, 2));
        JLabelCrupier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Crupier1.jpg"))); // NOI18N
        JLabelCrupier.setLabelFor(JLabelCrupier);
        JLabelCrupier.setToolTipText("");
        JLabelCrupier.setAlignmentY(0.0F);
        JLabelCrupier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(27, 2, 2), new java.awt.Color(27, 2, 2), new java.awt.Color(27, 2, 2), new java.awt.Color(27, 2, 2)));
        JLabelCrupier.setIconTextGap(0);
        JLabelCrupier.setOpaque(true);
        JLabelCrupier.setPreferredSize(new java.awt.Dimension(640, 400));

        jPanelBottom.setBackground(new java.awt.Color(27, 2, 2));
        jPanelBottom.setAlignmentX(0.0F);
        jPanelBottom.setAlignmentY(0.0F);
        jPanelBottom.setPreferredSize(new java.awt.Dimension(640, 160));

        javax.swing.GroupLayout jPanelBottomLayout = new javax.swing.GroupLayout(jPanelBottom);
        jPanelBottom.setLayout(jPanelBottomLayout);
        jPanelBottomLayout.setHorizontalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelBottomLayout.setVerticalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jPanelRight.setBackground(new java.awt.Color(27, 2, 2));
        jPanelRight.setPreferredSize(new java.awt.Dimension(140, 0));

        jButtonRules.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonRules.setForeground(new java.awt.Color(255, 51, 51));
        jButtonRules.setText("Rules");
        jButtonRules.setContentAreaFilled(false);
        jButtonRules.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRules.setPreferredSize(new java.awt.Dimension(80, 24));
        jButtonRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRulesActionPerformed(evt);
            }
        });

        jButtonInfo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonInfo.setForeground(new java.awt.Color(255, 51, 51));
        jButtonInfo.setText("Info");
        jButtonInfo.setToolTipText("");
        jButtonInfo.setAlignmentY(0.0F);
        jButtonInfo.setBorderPainted(false);
        jButtonInfo.setContentAreaFilled(false);
        jButtonInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInfo.setIconTextGap(0);
        jButtonInfo.setName("JButtonInfo"); // NOI18N
        jButtonInfo.setPreferredSize(new java.awt.Dimension(80, 24));
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });

        jButtonPlay.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonPlay.setForeground(new java.awt.Color(255, 51, 51));
        jButtonPlay.setText("Play");
        jButtonPlay.setToolTipText("Play");
        jButtonPlay.setAlignmentY(0.0F);
        jButtonPlay.setBorderPainted(false);
        jButtonPlay.setContentAreaFilled(false);
        jButtonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlay.setIconTextGap(0);
        jButtonPlay.setName("JButtonPlay"); // NOI18N
        jButtonPlay.setPreferredSize(new java.awt.Dimension(91, 24));
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(27, 2, 2));
        jPasswordField1.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 53, 53));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("User");
        jPasswordField1.setBorder(null);
        jPasswordField1.setCaretColor(new java.awt.Color(27, 2, 2));
        jPasswordField1.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jPasswordField1.setOpaque(false);
        jPasswordField1.setPreferredSize(new java.awt.Dimension(91, 24));
        jPasswordField1.setSelectedTextColor(new java.awt.Color(255, 51, 51));
        jPasswordField1.setSelectionColor(new java.awt.Color(255, 51, 51));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jTextFieldTexas.setEditable(false);
        jTextFieldTexas.setBackground(new java.awt.Color(27, 2, 2));
        jTextFieldTexas.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jTextFieldTexas.setForeground(new java.awt.Color(255, 51, 51));
        jTextFieldTexas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTexas.setText("Texas Hold'em");
        jTextFieldTexas.setBorder(null);
        jTextFieldTexas.setOpaque(false);
        jTextFieldTexas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTexasActionPerformed(evt);
            }
        });

        jTextFieldPoker.setEditable(false);
        jTextFieldPoker.setBackground(new java.awt.Color(27, 2, 2));
        jTextFieldPoker.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jTextFieldPoker.setForeground(new java.awt.Color(255, 51, 51));
        jTextFieldPoker.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPoker.setText("Poker Game");
        jTextFieldPoker.setBorder(null);
        jTextFieldPoker.setOpaque(false);
        jTextFieldPoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPokerActionPerformed(evt);
            }
        });

        jTextFieldLogin.setEditable(false);
        jTextFieldLogin.setBackground(new java.awt.Color(27, 2, 2));
        jTextFieldLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTextFieldLogin.setForeground(new java.awt.Color(255, 53, 53));
        jTextFieldLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLogin.setText("Login");
        jTextFieldLogin.setBorder(null);
        jTextFieldLogin.setPreferredSize(new java.awt.Dimension(91, 24));
        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonRules, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jTextFieldPoker, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTexas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextFieldTexas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonRules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonInfo.getAccessibleContext().setAccessibleName("JButtonInfo");
        jButtonInfo.getAccessibleContext().setAccessibleDescription("JButtonInfo");

        jPanelLeft.setBackground(new java.awt.Color(27, 2, 2));

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanelUp.setBackground(new java.awt.Color(27, 2, 2));
        jPanelUp.setPreferredSize(new java.awt.Dimension(640, 20));

        javax.swing.GroupLayout jPanelUpLayout = new javax.swing.GroupLayout(jPanelUp);
        jPanelUp.setLayout(jPanelUpLayout);
        jPanelUpLayout.setHorizontalGroup(
            jPanelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelUpLayout.setVerticalGroup(
            jPanelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JLabelCrupier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
            .addComponent(jPanelUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelUp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLabelCrupier, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jPanelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("inicio");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRulesActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        // TODO add your handling code here:
        
        JDialogInfo.setVisible(true);
        
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jTextFieldTexasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTexasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTexasActionPerformed

    private void jTextFieldPokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPokerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPokerActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
            
                    // Se obtiene un Clip de sonido
                    Clip sonido = AudioSystem.getClip();
            
                    // Se carga con un fichero wav
                    sonido.open(AudioSystem.getAudioInputStream(new File(
                    "C:\\Users\\Aspire\\Documents\\NetBeansProjects\\Poker\\src\\Audios\\LoveIsBlue.wav")));
            
                    // Comienza la reproducción
                    sonido.start();
                    
                    sonido.loop(Clip.LOOP_CONTINUOUSLY);
                    
                } catch (Exception e) {
                    System.out.println("" + e); 
                }
                
                
                try{ 
                    Thread.sleep(1000); 
                } 
                catch(InterruptedException e ){ 
                    System.out.println("" + e);
                }
                
                new Inicio().setVisible(true);    
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDialogInfo;
    private javax.swing.JLabel JLabelCrupier;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonRules;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelUp;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldPoker;
    private javax.swing.JTextField jTextFieldTexas;
    // End of variables declaration//GEN-END:variables
}
